### ISSUE TITLE
RNN Multi GPU error

### ISSUE THREAD

**Issue by samukie** [joeynmt/joeynmt#117]
**Describe the bug**
When trying to use multiple GPUs to train RNN models, I get the following error: 

> AssertionError: Caught AssertionError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/students/kiegeland/anaconda3/envs/nmt/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/students/kiegeland/anaconda3/envs/nmt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/students/kiegeland/test/joeynmt/joeynmt/model.py", line 87, in forward
    trg_mask=kwargs["trg_mask"])
  File "/home/students/kiegeland/test/joeynmt/joeynmt/model.py", line 147, in _encode_decode
    trg_mask=trg_mask)
  File "/home/students/kiegeland/test/joeynmt/joeynmt/model.py", line 186, in _decode
    trg_mask=trg_mask)
  File "/home/students/kiegeland/anaconda3/envs/nmt/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/students/kiegeland/test/joeynmt/joeynmt/decoders.py", line 340, in forward
    prev_att_vector=prev_att_vector)
  File "/home/students/kiegeland/test/joeynmt/joeynmt/decoders.py", line 192, in _check_shapes_input_forward
    assert src_mask.shape[2] == encoder_output.shape[1]
AssertionError

It seems like the src_length is different for each device which results in different shapes for the encoder output.
Is there anything else I need to configure?

**To Reproduce**
Training the reverse experiment using 2 gpus on version=1.0
[node_configuration.txt](https://github.com/joeynmt/joeynmt/files/5493901/train_reverse_sh.txt)

**Logged output**
[error_log.txt](https://github.com/joeynmt/joeynmt/files/5493824/reverse_error.txt)

**Comment by may-** [comment]
Hi @samukie  actually, I only tested my multi-gpu implementation on transformer models. For reverse problem, I confirmed that this configuration works: https://github.com/may-/joeynmt/blob/master/configs/reverse.yaml
[train.log](https://github.com/joeynmt/joeynmt/files/5496334/train.log)

Do you need RNN on multi-gpu? Currently I have no time, but I will put this in my mid-term todos.

**Comment by samukie** [comment]
Hi @may-, thank you for the quick reply! 
The configuration works and `transformer_iwslt14_deen_bpe.yaml` also does, so it seems like the problem only occurs when using RNNs. 
I'll just stick to the transfomer models when using multi-gpu.

**Comment by may-** [comment]
Hi @samukie ,
I fixed this bug. please check my pull request https://github.com/joeynmt/joeynmt/pull/132.

**Comment by samukie** [comment]
Oh nice, thank you!!
