### ISSUE TITLE
Missing type prediction during testing

### ISSUE THREAD

**Issue by turkicinterlingua** [joeynmt/joeynmt#130]
**Describe the bug**
While running the testing, it throws an error like below saying that it is missing a required argument 'batch_class'

`! cd joeynmt; python3 -m joeynmt test "$gdrive_path/models/${src}${tgt}_transformer/config.yaml"`

2021-01-16 15:01:14,414 - INFO - root - Hello! This is Joey-NMT (version 1.0).
2021-01-16 15:01:14,418 - INFO - joeynmt.data - building vocabulary...
2021-01-16 15:01:26,060 - INFO - joeynmt.data - loading dev data...
2021-01-16 15:01:26,089 - INFO - joeynmt.data - loading test data...
2021-01-16 15:01:26,102 - INFO - joeynmt.data - data loaded.
2021-01-16 15:01:26,121 - INFO - joeynmt.prediction - Process device: cuda, n_gpu: 1, batch_size per device: 3600
2021-01-16 15:01:32,448 - INFO - joeynmt.prediction - Decoding on dev set (data/uzen/dev.bpe.en)...
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/joeynmt/joeynmt/__main__.py", line 41, in <module>
    main()
  File "/content/joeynmt/joeynmt/__main__.py", line 32, in main
    output_path=args.output_path, save_attention=args.save_attention)
  File "/content/joeynmt/joeynmt/prediction.py", line 325, in test
    bpe_type=bpe_type, sacrebleu=sacrebleu, n_gpu=n_gpu)
TypeError: validate_on_data() missing 1 required positional argument: 'batch_class'

**To Reproduce**
1. Translation task with over 500k examples
2. config file looks like this:

# Create the config
config = """
name: "{name}_transformer"

data:
    src: "{source_language}"
    trg: "{target_language}"
    train: "data/{name}/train.bpe"
    dev:   "data/{name}/dev.bpe"
    test:  "data/{name}/test.bpe"  # change this to data/{name}/test2.bpe so that you can test it on Ted Talks
    level: "bpe"
    lowercase: False
    max_sent_length: 128
    src_vocab: "data/{name}/vocab.txt"
    trg_vocab: "data/{name}/vocab.txt"

testing:
    beam_size: 5
    alpha: 1.0
    sacrebleu:                      # sacrebleu options
        remove_whitespace: True     # `remove_whitespace` option in sacrebleu.corpus_chrf() function (defalut: True)
        tokenize: "none"            # `tokenize` option in sacrebleu.corpus_bleu() function (options include: "none" (use for already tokenized test data), "13a" (default minimal tokenizer), "intl" which mostly does punctuation and unicode, etc) 

training:
    load_model: "{gdrive_path}/models/{name}_transformer/best.ckpt" # if uncommented, load a pre-trained model from this checkpoint
    random_seed: 42
    optimizer: "adam"
    normalization: "tokens"
    adam_betas: [0.9, 0.998] 
    scheduling: "plateau"           
    patience: 5                     
    learning_rate_factor: 0.5       
    learning_rate_warmup: 4000     
    decrease_factor: 0.7
    loss: "crossentropy"
    learning_rate: 0.0003          
    learning_rate_min: 0.00000001
    weight_decay: 0.0
    label_smoothing: 0.1
    batch_size: 4096
    batch_type: "token"
    eval_batch_size: 3600
    eval_batch_type: "token"
    batch_multiplier: 8
    early_stopping_metric: "ppl"
    epochs: 100                     
    validation_freq: 1000          
    logging_freq: 100
    eval_metric: "bleu"
    model_dir: "{gdrive_path}/models/{name}_transformer2"
    overwrite: True               # TODO: Set to True if you want to overwrite possibly existing models. 
    shuffle: True
    use_cuda: True
    fp16: True
    max_output_length: 128
    print_valid_sents: [0, 1, 2, 3]
    keep_last_ckpts: 3

model:
    initializer: "xavier"
    bias_initializer: "zeros"
    init_gain: 1.0
    embed_initializer: "xavier"
    embed_init_gain: 1.0
    tied_embeddings: True
    tied_softmax: True
    encoder:
        type: "transformer"
        num_layers: 6
        num_heads: 4             
        embeddings:
            embedding_dim: 512   
            scale: True
            dropout: 0.2
        # typically ff_size = 4 x hidden_size
        hidden_size: 512         
        ff_size: 2048            
        dropout: 0.3
    decoder:
        type: "transformer"
        num_layers: 6
        num_heads: 4             
        embeddings:
            embedding_dim: 512    
            scale: True
            dropout: 0.2
        # typically ff_size = 4 x hidden_size
        hidden_size: 512         
        ff_size: 2048           
        dropout: 0.3
"""

**System (please complete the following information):**
 - Google Colab 
 - Python 3.6

**Additional context**
Installing from joeynmt from pip

**Comment by turkicinterlingua** [comment]
This was a quick fix! Basically, I needed to include 'batch_type': 'sentence' or  'eval_batch_type': 'sentence'  in the training section
