### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ShadowVicky** [joeynmt/joeynmt#177]
/content
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/joeynmt/joeynmt/__main__.py", line 64, in <module>
    main()
  File "/content/joeynmt/joeynmt/__main__.py", line 44, in main
    train(cfg_file=args.config_path, skip_test=args.skip_test)
  File "/content/joeynmt/joeynmt/training.py", line 809, in train
    overwrite=cfg["training"].get("overwrite", False),
  File "/content/joeynmt/joeynmt/helpers.py", line 55, in make_model_dir
    model_dir.mkdir()
  File "/usr/lib/python3.7/pathlib.py", line 1273, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/content/joeynmt/models/enas_transformer'

**Comment by may-** [comment]
Hi,

Thank you for trying the new version und notifying the problem.
Are you sure the parent directory `/content/joeynmt/models` exists?
Currently, joeynmt doesn't create a model dir recursively.

@juliakreutzer Do you think we should enable a recursive dir creation?
(set parents=True in Path.mkdir() func. https://docs.python.org/3/library/pathlib.html#pathlib.Path.mkdir)

**Comment by juliakreutzer** [comment]
@may- yes I'd vote for recursive dir creation!

**Comment by may-** [comment]
@juliakreutzer ok, I'll raise a pull request, then.

**Comment by juliakreutzer** [comment]
Thanks!

**Comment by juliakreutzer** [comment]
Fixed in #180
