### ISSUE TITLE
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by sinaahmadi** [joeynmt/joeynmt#200]
Hi,

I am trying to train a model on GPU. However, I am having the following error:
```
2022-12-29 15:25:59,295 - INFO - joeynmt.training - Train stats:
	device: cuda
	n_gpu: 1
	16-bits training: False
	gradient accumulation: 1
	batch size per device: 10
	effective batch size (w. parallel & accumulation): 10
2022-12-29 15:25:59,295 - INFO - joeynmt.training - EPOCH 1
Traceback (most recent call last):
  File "/opt/sw/spack/apps/linux-rhel8-x86_64_v2/gcc-10.3.0/python-3.9.9-jh/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/sw/spack/apps/linux-rhel8-x86_64_v2/gcc-10.3.0/python-3.9.9-jh/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/scratch/sahmad46/venvs/torch1/lib/python3.9/site-packages/joeynmt/__main__.py", line 64, in <module>
    main()
  File "/scratch/sahmad46/venvs/torch1/lib/python3.9/site-packages/joeynmt/__main__.py", line 44, in main
    train(cfg_file=args.config_path, skip_test=args.skip_test)
  File "/scratch/sahmad46/venvs/torch1/lib/python3.9/site-packages/joeynmt/training.py", line 829, in train
    trainer.train_and_validate(train_data=train_data, valid_data=dev_data)
  File "/scratch/sahmad46/venvs/torch1/lib/python3.9/site-packages/joeynmt/training.py", line 457, in train_and_validate
    batch.sort_by_src_length()
  File "/scratch/sahmad46/venvs/torch1/lib/python3.9/site-packages/joeynmt/batch.py", line 144, in sort_by_src_length
    sorted_trg_length = self.trg_length[perm_index]
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
```

I'll be happy to share more information if need be.

**Comment by sinaahmadi** [comment]
Sorry, I forgot to install `torch` as suggested in the [README file](https://github.com/joeynmt/joeynmt). That solved the problem.

At least, I hope the issue saves some time for future users facing the same problem 😊
