### ISSUE TITLE
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by matthew-burnard** [joeynmt/joeynmt#210]
**Describe the bug**
No idea if this is an actual bug or just something I'm doing wrong with the config.
Trying to run a transformer model on my GPU I get the following error
```RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)```
at the start of the first epoch.
Full traceback bellow.

**To Reproduce**
Joeynmt version: 2.1.0
pytorch: 1.13.1+cu117
CUDA: 11.7
With the following config file
```
name: "abbreviation_generation_transformer_copy_model"
joeynmt_version: "2.1.0"

data:
    train: "data/train"
    dev:  "data/dev"
    test: "data/test"
    dataset_type: "plain"
    src:
        lang: "src"
        max_length: 100
        min_length: 1
        level: "word"
        voc_limit: 400
        voc_min_freq: 1
        voc_file: "data/vocab.txt"
    
    trg:
        lang: "tgt"
        max_length: 100
        min_length: 1
        level: "word"
        voc_limit: 400
        voc_min_freq: 1
        voc_file: "data/vocab.txt"
    
testing:
    n_best: 1
    beam_size: 5
    beam_alpha: 1.0
    batch_size: 10
    batch_type: "sentence"
    eval_metrics: ["token_accuracy"]
    max_output_length: 100
    return_prob: "none"

training:
    #random_seed: 42
    optimizer: "adam"
    learning_rate: 0.01
    learning_rate_min: 0.0001
    clip_grad_norm: 1.0
    weight_decay: 0.
    batch_size: 100
    batch_type: "sentence"
    normalization: "batch"
    scheduling: "plateau"
    patience: 3
    decrease_factor: 0.5
    epochs: 1000
    validation_freq: 100
    logging_freq: 50
    early_stopping_metric: "acc"
    model_dir: "copy-model-transformer"
    overwrite: True #Only set True when debugging
    shuffle: True
    use_cuda: True
    fp16: False
    print_valid_sents: [0, 3, 6]
    keep_best_chpts: 1

model:
    initializer: "xavier_uniform"
    init_weight: 0.01
    init_gain: 1.0
    bias_initializer: "zeros"
    embed_initializer: "normal"
    embed_init_weight: 0.1
    embed_init_gain: 1.0
    init_rnn_orthogonal: False
    lstm_forget_gate: 1.
    tied_embeddings: False
    tied_softmax: False
    encoder:
        type: "transformer"
        num_layers: 3
        num_heads: 4
        embeddings:
            embedding_dim: 64
            scale: False
            freeze: False
            #load_pretrained: No pretrained embeddings exist
        hidden_size: 64
        ff_size: 64
        dropout: 0.1
        freeze: False
        layer_norm: "pre"
    decoder:
        type: "transformer"
        num_layers: 3
        num_heads: 4
        embeddings:
            embedding_dim: 64
            scale: False
            freeze: False
            #load_pretrained: No pretrained embeddings exist
        hidden_size: 64
        dropout: 0.2
        freese: False
        layer_norm: "pre"
```

**Logged output**
Full traceback
```
Traceback (most recent call last):
  File "____\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "____\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "____\src\venv-gpu\lib\site-packages\joeynmt\__main__.py", line 64, in <module>
    main()
  File "____\src\venv-gpu\lib\site-packages\joeynmt\__main__.py", line 44, in main
    train(cfg_file=args.config_path, skip_test=args.skip_test)
  File "____\src\venv-gpu\lib\site-packages\joeynmt\training.py", line 829, in train
    trainer.train_and_validate(train_data=train_data, valid_data=dev_data)
  File "____\src\venv-gpu\lib\site-packages\joeynmt\training.py", line 457, in train_and_validate
    batch.sort_by_src_length()
  File "____\src\venv-gpu\lib\site-packages\joeynmt\batch.py", line 144, in sort_by_src_length
    sorted_trg_length = self.trg_length[perm_index]
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
```

**Comment by may-** [comment]
Hi @matthew-burnard,

Could you please check if your `train.log` indicates the correct device type and gpu device count? Something like
```
2023-03-12 05:23:05,676 - INFO - joeynmt.training - Train stats:
	device: cuda
	n_gpu: 1
	16-bits training: False
	gradient accumulation: 1
	batch size per device: 100
	effective batch size (w. parallel & accumulation): 100
```
(Search the line of "Train stats")

**Comment by matthew-burnard** [comment]
```
2023-03-12 04:29:23,953 - INFO - joeynmt.training - Train stats:
	device: cuda
	n_gpu: 1
	16-bits training: True
	gradient accumulation: 1
	batch size per device: 5
	effective batch size (w. parallel & accumulation): 5
```

**Comment by matthew-burnard** [comment]
Here you go.
```
2023-03-12 03:41:18,543 - INFO - joeynmt.training - Train stats:
        device: cuda
        n_gpu: 1
        16-bits training: False
        gradient accumulation: 1
        batch size per device: 5
        effective batch size (w. parallel & accumulation): 5
```

**Comment by may-** [comment]
Ah, I guess this was a bug fixed last month. https://github.com/joeynmt/joeynmt/issues/200


https://github.com/joeynmt/joeynmt/blob/0f57e93604b58cefadf48583f47a322819c59850/joeynmt/batch.py#L79-L89

Could you please check if the line 88 `self.trg_length = self.trg_length.to(device)` exists in the code? ("____\src\venv-gpu\lib\site-packages\joeynmt\batch.py") If not, please add the line, or clone the latest repo and install joeynmt from source.

**Comment by matthew-burnard** [comment]
Confirmed, adding that line to `\venv-gpu\lib\site-packages\joeynmt\batch.py` solved the problem. Thank you for your help!

**Comment by juliakreutzer** [comment]
I'll update the pypi! Sorry for the delay.
