### ISSUE TITLE
Size mismatch during validation

### ISSUE THREAD

**Issue by yukiyakiZ** [joeynmt/joeynmt#98]
**Describe the bug**
The model ran perfectly with some of my dataset. However, for one of the datasets, the following bug appears. The log is as below.

**Logged output**
`2020-05-24 18:50:40,236 EPOCH 1
2020-05-24 18:50:40,706 Epoch   1 Step:       10 Batch Loss:   129.308456 Tokens per Sec:     6443, Lr: 0.000014
2020-05-24 18:50:41,086 Epoch   1 Step:       20 Batch Loss:    88.039078 Tokens per Sec:     8751, Lr: 0.000028
2020-05-24 18:50:41,476 Epoch   1 Step:       30 Batch Loss:    94.100029 Tokens per Sec:     7615, Lr: 0.000042
2020-05-24 18:50:41,863 Epoch   1 Step:       40 Batch Loss:   128.856537 Tokens per Sec:     7575, Lr: 0.000056
2020-05-24 18:50:42,255 Epoch   1 Step:       50 Batch Loss:   114.877518 Tokens per Sec:     8100, Lr: 0.000070
2020-05-24 18:50:42,737 Epoch   1 Step:       60 Batch Loss:    85.376068 Tokens per Sec:     8259, Lr: 0.000084
2020-05-24 18:50:43,267 Epoch   1 Step:       70 Batch Loss:   298.312286 Tokens per Sec:     5568, Lr: 0.000098
2020-05-24 18:50:43,812 Epoch   1 Step:       80 Batch Loss:   101.327324 Tokens per Sec:     6123, Lr: 0.000112
2020-05-24 18:50:44,323 Epoch   1 Step:       90 Batch Loss:   172.604233 Tokens per Sec:     6887, Lr: 0.000126
2020-05-24 18:50:44,822 Epoch   1 Step:      100 Batch Loss:    93.117615 Tokens per Sec:     5750, Lr: 0.000140
Traceback (most recent call last):
  File "/home/xingyuaz/anaconda3/envs/my_fisrt_env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/xingyuaz/anaconda3/envs/my_fisrt_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xingyuaz/test_joeynmt/joeynmt/joeynmt/__main__.py", line 41, in <module>
    main()
  File "/home/xingyuaz/test_joeynmt/joeynmt/joeynmt/__main__.py", line 29, in main
    train(cfg_file=args.config_path)
  File "/home/xingyuaz/test_joeynmt/joeynmt/joeynmt/training.py", line 650, in train
    trainer.train_and_validate(train_data=train_data, valid_data=dev_data)
  File "/home/xingyuaz/test_joeynmt/joeynmt/joeynmt/training.py", line 375, in train_and_validate
    batch_type=self.eval_batch_type
  File "/home/xingyuaz/test_joeynmt/joeynmt/joeynmt/prediction.py", line 98, in validate_on_data
    batch, loss_function=loss_function)
  File "/home/xingyuaz/test_joeynmt/joeynmt/joeynmt/model.py", line 133, in get_loss_for_batch
    trg_mask=batch.trg_mask)
  File "/home/xingyuaz/test_joeynmt/joeynmt/joeynmt/model.py", line 74, in forward
    src_mask=src_mask)
  File "/home/xingyuaz/test_joeynmt/joeynmt/joeynmt/model.py", line 92, in encode
    return self.encoder(self.src_embed(src), src_length, src_mask)
  File "/home/xingyuaz/anaconda3/envs/my_fisrt_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xingyuaz/test_joeynmt/joeynmt/joeynmt/encoders.py", line 216, in forward
    x = self.pe(embed_src)  # add position encoding to word embeddings
  File "/home/xingyuaz/anaconda3/envs/my_fisrt_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xingyuaz/test_joeynmt/joeynmt/joeynmt/transformer_layers.py", line 159, in forward
    return emb + self.pe[:, :emb.size(1)]
RuntimeError: The size of tensor a (9098) must match the size of tensor b (5000) at non-singleton dimension 1`

**Comment by bastings** [comment]
Hi! It looks like you might be using embeddings with size 9098? What hyper-parameters are you using?

**Comment by yukiyakiZ** [comment]
Thank you for your reply. The embedding size I used is 128 instead of 9098. 
The yaml file I used is attached.
[my.log](https://github.com/joeynmt/joeynmt/files/4679420/my.log)

**Comment by juliakreutzer** [comment]
Hi @yukiyakiZ thanks for sharing the yaml. It is not directly apparent for me what could cause this error. Maybe some issue with batching? 
Can you try changing the batch size and see if it changes? Either the error or when it occurs?

BTW I noticed a typo in your config though: "use_cuda: Ture"

**Comment by juliakreutzer** [comment]
Closing due to inactivity.
